// apps/hackernews-react/src/components/story.tsx
import { formatDistance } from 'date-fns'
import styled from '@emotion/styled'
import { Link } from 'react-router'
import type { StoryData } from '@repo/hn-core'

interface StoryProps {
  data: StoryData
  showText?: boolean
}

const Title = styled.h2`
  display: inline;
  color: var(--secondary-color);
  font-size: 1em;
  font-weight: 400;
  line-height: 1.25em;
`

const TitleLink = styled.a`
  &:hover {
    color: var(--secondary-color);
  }
`

const Subtitle = styled.p`
  margin-top: 5px;
  color: var(--gray);
  font-size: 11px;

  & > a {
    color: var(--gray);
  }

  @media only screen and (max-width: 400px) {
    font-size: 11px;
  }
`

const Content = styled.article`
  width: calc(100% - 25px);
  margin-left: 5px;
`

const Text = styled.div`
  margin-top: 15px;
  margin-left: 6px;
  font-size: 12px;
  color: var(--gray);

  & p {
    margin: 10px 0;
  }

  & code,
  & pre {
    white-space: pre-wrap;
  }
`

function Information({ data }: { data: StoryData }) {
  const createdTime = data.time && formatDistance(data.time * 1000, new Date(), { addSuffix: true })

  if (data.type === 'job') return <Subtitle>{createdTime}</Subtitle>

  const userLink = (
    <Link to={`/user/${data.by}`}>
      <b>{data.by}</b>
    </Link>
  )

  return data.descendants && data.descendants > 0 ? (
    <Subtitle>
      {data.score} points by {userLink} {createdTime} |{' '}
      <Link to={`/comments/${data.id}`}>{data.descendants} comments</Link>
    </Subtitle>
  ) : (
    <Subtitle>
      {data.score} points by {userLink} {createdTime}
    </Subtitle>
  )
}

export default function Story({ data, showText = false }: StoryProps) {
  if (data.dead || data.deleted) return null

  return (
    <>
      <Content data-testid={`story-${data.id}`}>
        <TitleLink
          href={data.url ? data.url : `/comments/${data.id}`}
          target="_blank"
          rel="noreferrer"
        >
          <Title>{data.title}</Title>
        </TitleLink>
        <Information data={data} />
      </Content>
      {showText && data.text && <Text dangerouslySetInnerHTML={{ __html: data.text }} />}
    </>
  )
}

// apps/hackernews-vue/src/components/story/story.vue
<script setup lang="ts">
  import type { StoryData } from '@repo/hn-core'
  import Info from './info.vue'

  defineProps<{
    story: StoryData
    showText?: boolean
  }>()
</script>

<template>
  <article class="content">
    <a v-if="story.url" :href="story.url" class="title-link" target="_blank" rel="noreferrer">
      <h2 class="title">{{ story.title }}</h2>
    </a>
    <router-link v-else :to="`/comments/${story.id}`" class="title-link" target="_blank" rel="noreferrer">
      <h2 class="title">{{ story.title }}</h2>
    </router-link>
    <Info :story="story" />
  </article>
  <div class="text" v-if="showText && story.text" v-html="story.text" />
</template>

<style scoped>
  .title {
    display: inline;
    color: var(--secondary-color);
    font-size: 1em;
    font-weight: 400;
    line-height: 1.25em;
  }

  .title-link:hover {
    color: var(--secondary-color);
  }

  .content {
    width: calc(100% - 25px);
    margin-left: 5px;
  }

  .text {
    margin-top: 15px;
    margin-left: 6px;
    font-size: 12px;
    color: var(--gray);
  }

  .text :deep(p) {
    margin: 10px 0;
  }

  .text :deep(code), .text :deep(pre) {
    white-space: pre-wrap;
  }

</style>
