// apps/hackernews-react/src/app.tsx
import styled from '@emotion/styled'
import { Routes, Route } from 'react-router'
import NavBar from './components/navbar'
import Stories from './stories'
import Comments from './comments'
import Users from './users'

const Header = styled.header`
  padding: 10px;
  background-color: var(--dark-bg);
`

const Footer = styled.footer`
  border-top: 2px solid var(--primary-color);
  margin: 0 5px;
  padding: 10px 0;
  text-align: center;
  font-size: 11px;
`

const App = () => (
  <>
    <Header>
      <NavBar />
    </Header>
    <Routes>
      <Route index element={<Stories type='topstories' />} />
      <Route path='/topstories' element={<Stories type='topstories' />} />
      <Route path='/newstories' element={<Stories type='newstories' />} />
      <Route path='/beststories' element={<Stories type='beststories' />} />
      <Route path='/askstories' element={<Stories type='askstories' />} />
      <Route path='/showstories' element={<Stories type='showstories' />} />
      <Route path='/jobstories' element={<Stories type='jobstories' />} />
      <Route path='/comments/:itemid' element={<Comments />} />
      <Route path='/user/:userid' element={<Users />} />
    </Routes>
    <Footer aria-label='footer'>
      ©{new Date().getFullYear()} Karsanda
      <a href="https://github.com/karsanda/monorepo/tree/main/apps/hackernews-react">
        Hacker News - React
      </a>
    </Footer>
  </>
)

export default App

// apps/hackernews-vue/src/app.vue
<script setup lang="ts">
  import Navbar from './components/navbar.vue'
</script>

<template>
  <header class="header">
    <Navbar />
  </header>
  <router-view />
  <footer class="footer">
    ©{{ new Date().getFullYear() }} Karsanda
    <a href="https://github.com/karsanda/monorepo/tree/main/apps/hackernews-vue">
      Hacker News - Vue 
    </a>
  </footer>
</template>

<style scoped>
  .header {
    padding: 10px;
    background-color: var(--dark-bg);
  }

  .footer {
    border-top: 2px solid var(--primary-color);
    margin: 0 5px;
    padding: 10px 0;
    text-align: center;
    font-size: 11px;
  }
</style>
