// apps/hn-react/src/app/app.tsx
import styled from '@emotion/styled'
import useFetch from '../hooks/useFetch'
import Item from './item'

const Header = styled.header`
  padding: 5px 10px;
  background-color: var(--dark-bg);
  color: var(--primary-color);
`

const Main = styled.main`
  padding: 10px 15px 15px 0;
`

const Footer = styled.main`
  border-top: 1px solid #cccccc;
  margin: 0 15px;
  padding: 10px 0;
  text-align: center;
  font-size: 0.8em;
`

const List = styled.ol`
  margin: 0;
`

const TOP_STORIES_API = 'https://hacker-news.firebaseio.com/v0/topstories.json'

function App() {
  const { data } = useFetch<string[]>(TOP_STORIES_API)
  return (
    <>
      <Header>
        <h1>HN - React</h1>
      </Header>
      <Main>
        <List>{data?.splice(0, 30).map(id => <Item key={id} id={id} />)}</List>
      </Main>
      <Footer>
        ©{new Date().getFullYear()} Karsanda | <a href='https://github.com/karsanda/monorepo/tree/main/apps/hn-react'>HN - React</a>
      </Footer>
    </>
  )
}

export default App

// apps/hackernews-vue/src/app.vue
<script setup lang="ts">
  import Navbar from './components/navbar.vue'
</script>

<template>
  <header class="header">
    <Navbar />
  </header>
  <router-view />
  <footer class="footer">
    ©{{ new Date().getFullYear() }} Karsanda
    <a href="https://github.com/karsanda/monorepo/tree/main/apps/hackernews-vue">
      Hacker News - Vue 
    </a>
  </footer>
</template>

<style scoped>
  .header {
    padding: 10px;
    background-color: var(--dark-bg);
  }

  .footer {
    border-top: 2px solid var(--primary-color);
    margin: 0 5px;
    padding: 10px 0;
    text-align: center;
    font-size: 11px;
  }
</style>
