// apps/hackernews-solid/src/components/comment.tsx
import type { ThreadComment } from '@repo/hn-core'
import { createSignal, For, Show } from 'solid-js'
import { RelTime } from './rel-time'

export function Comment(props: { comment: ThreadComment }) {
  const [collapsed, setCollapsed] = createSignal(false)

  return (
    // Deleted comments are only worth showing when they have replies.
    <Show when={props.comment.by || props.comment.kids.length}>
      <article class="comment">
        <div class="comment-header">
          <button
            class="collapse-button"
            type="button"
            aria-expanded={!collapsed()}
            aria-label={`${collapsed() ? 'Expand' : 'Collapse'} comment by ${props.comment.by ?? 'deleted user'}`}
            onClick={() => setCollapsed(!collapsed())}
          >
            <span aria-hidden="true">{collapsed() ? '▶' : '▼'}</span>
          </button>
          <Show when={props.comment.by} fallback="[deleted]">
            {(by) => (
              <a href={`/user/${by()}`}>
                <strong>{by()}</strong>
              </a>
            )}
          </Show>
          &nbsp;
          <RelTime unix={props.comment.time} />
        </div>

        <Show when={!collapsed()}>
          <Show when={props.comment.text}>
            {(text) => <div class="comment-content" innerHTML={text()} />}
          </Show>
          <Show when={props.comment.kids.length}>
            <div class="comment-children">
              <For each={props.comment.kids}>{(kid) => <Comment comment={kid} />}</For>
            </div>
          </Show>
        </Show>
      </article>
    </Show>
  )
}

// apps/hackernews-qwik/src/components/comment.tsx
import { component$, useSignal } from '@builder.io/qwik'
import { Link } from '@builder.io/qwik-city'
import type { ThreadComment } from '@repo/hn-core'
import { RelTime } from './rel-time'

export const Comment = component$<{ comment: ThreadComment }>(({ comment }) => {
  const collapsed = useSignal(false)

  // Deleted comments are only worth showing when they have replies.
  if (!comment.by && !comment.kids.length) return null

  return (
    <article class="comment">
      <div class="comment-header">
        <button
          class="collapse-button"
          type="button"
          aria-expanded={!collapsed.value}
          aria-label={`${collapsed.value ? 'Expand' : 'Collapse'} comment by ${comment.by ?? 'deleted user'}`}
          onClick$={() => (collapsed.value = !collapsed.value)}
        >
          <span aria-hidden="true">{collapsed.value ? '▶' : '▼'}</span>
        </button>
        {comment.by ? (
          <Link href={`/user/${comment.by}`} prefetch={false}>
            <strong>{comment.by}</strong>
          </Link>
        ) : (
          '[deleted]'
        )}
        &nbsp;
        <RelTime unix={comment.time} />
      </div>

      {!collapsed.value && (
        <>
          {comment.text && <div class="comment-content" dangerouslySetInnerHTML={comment.text} />}
          {comment.kids.length > 0 && (
            <div class="comment-children">
              {comment.kids.map((kid) => (
                <Comment key={kid.id} comment={kid} />
              ))}
            </div>
          )}
        </>
      )}
    </article>
  )
})
