// apps/hackernews-next/src/components/load-error.tsx
'use client'

export function LoadError({ what }: { what: string }) {
  return (
    <p className="status" role="alert">
      Couldn&apos;t load {what}. Hacker News may be slow right now;{' '}
      <button className="link-button" type="button" onClick={() => location.reload()}>
        try again
      </button>
      .
    </p>
  )
}

// apps/hackernews-qwik/src/components/load-error.tsx
import { component$ } from '@builder.io/qwik'

export const LoadError = component$<{ what: string }>(({ what }) => (
  <p class="status" role="alert">
    Couldn&apos;t load {what}. Hacker News may be slow right now;{' '}
    <button class="link-button" type="button" onClick$={() => location.reload()}>
      try again
    </button>
    .
  </p>
))
