// apps/hackernews-next/src/app/not-found.tsx
import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { title: 'Not found' }

export default function NotFound() {
  return (
    <div className="status">
      <h1>Not found</h1>
      <p>
        That page, story or user doesn&apos;t exist. <Link href="/">Back to top stories</Link>
      </p>
    </div>
  )
}

// apps/hackernews-qwik/src/components/not-found.tsx
import { component$ } from '@builder.io/qwik'
import { Link } from '@builder.io/qwik-city'

export const NotFound = component$(() => (
  <div class="status">
    <h1>Not found</h1>
    <p>
      That page, story or user doesn&apos;t exist. <Link href="/">Back to top stories</Link>
    </p>
  </div>
))
