// apps/hackernews-svelte/src/routes/search/+page.svelte
<script lang="ts">
  import { resolve } from '$app/paths'
  import Pager from '$lib/components/pager.svelte'
  import StoryList from '$lib/components/story-list.svelte'
  import { pageTitle } from '$lib/meta'
  import type { PageProps } from './$types'

  let { data }: PageProps = $props()

  const href = (page: number) =>
    `${resolve('/search')}?${new URLSearchParams({ q: data.query, page: String(page) })}`
</script>

<svelte:head>
  <title>{pageTitle(data.query ? `Search: ${data.query}` : 'Search')}</title>
</svelte:head>

<h1 class="visually-hidden">Search</h1>

{#if data.results}
  <StoryList stories={data.results.items} label="Search results" page={data.results.page} />
  <Pager page={data.results.page} pageCount={data.results.pageCount} {href} />
{:else}
  <p class="status">Type in the search box to find stories.</p>
{/if}

// apps/hackernews-next/src/app/search/page.tsx
import { getPage } from '@repo/hn-core'
import type { Metadata } from 'next'
import { Pager } from '@/components/pager'
import { StoryList } from '@/components/story-list'
import { loadSearch } from '@/lib/data'
import { param } from '@/lib/meta'

async function readParams(searchParams: PageProps<'/search'>['searchParams']) {
  const params = await searchParams
  return { query: param(params.q)?.trim() ?? '', page: getPage(param(params.page)) }
}

export async function generateMetadata({ searchParams }: PageProps<'/search'>): Promise<Metadata> {
  const { query } = await readParams(searchParams)
  return { title: query ? `Search: ${query}` : 'Search' }
}

export default async function SearchPage({ searchParams }: PageProps<'/search'>) {
  const { query, page } = await readParams(searchParams)
  const results = await loadSearch(query, page)
  const href = (p: number) => `/search?${new URLSearchParams({ q: query, page: String(p) })}`

  return (
    <>
      <h1 className="visually-hidden">Search</h1>
      {results ? (
        <>
          <StoryList stories={results.items} label="Search results" page={results.page} />
          <Pager page={results.page} pageCount={results.pageCount} href={href} />
        </>
      ) : (
        <p className="status">Type in the search box to find stories.</p>
      )}
    </>
  )
}
