// apps/hackernews-solid/src/components/comment.tsx
import type { ThreadComment } from '@repo/hn-core'
import { createSignal, For, Show } from 'solid-js'
import { RelTime } from './rel-time'

export function Comment(props: { comment: ThreadComment }) {
  const [collapsed, setCollapsed] = createSignal(false)

  return (
    // Deleted comments are only worth showing when they have replies.
    <Show when={props.comment.by || props.comment.kids.length}>
      <article class="comment">
        <div class="comment-header">
          <button
            class="collapse-button"
            type="button"
            aria-expanded={!collapsed()}
            aria-label={`${collapsed() ? 'Expand' : 'Collapse'} comment by ${props.comment.by ?? 'deleted user'}`}
            onClick={() => setCollapsed(!collapsed())}
          >
            <span aria-hidden="true">{collapsed() ? '▶' : '▼'}</span>
          </button>
          <Show when={props.comment.by} fallback="[deleted]">
            {(by) => (
              <a href={`/user/${by()}`}>
                <strong>{by()}</strong>
              </a>
            )}
          </Show>
          &nbsp;
          <RelTime unix={props.comment.time} />
        </div>

        <Show when={!collapsed()}>
          <Show when={props.comment.text}>
            {(text) => <div class="comment-content" innerHTML={text()} />}
          </Show>
          <Show when={props.comment.kids.length}>
            <div class="comment-children">
              <For each={props.comment.kids}>{(kid) => <Comment comment={kid} />}</For>
            </div>
          </Show>
        </Show>
      </article>
    </Show>
  )
}

// apps/hackernews-svelte/src/lib/components/comment.svelte
<script lang="ts">
  import { isoTime, timeAgo, type ThreadComment } from '@repo/hn-core'
  import { resolve } from '$app/paths'
  import Self from './comment.svelte'

  let { comment }: { comment: ThreadComment } = $props()

  let collapsed = $state(false)
</script>

<!-- Deleted comments are only worth showing when they have replies. -->
{#if comment.by || comment.kids.length}
  <article class="comment">
    <div class="comment-header">
      <button
        class="collapse-button"
        type="button"
        aria-expanded={!collapsed}
        aria-label="{collapsed ? 'Expand' : 'Collapse'} comment by {comment.by ?? 'deleted user'}"
        onclick={() => (collapsed = !collapsed)}
      >
        <span aria-hidden="true">{collapsed ? '▶' : '▼'}</span>
      </button>
      {#if comment.by}
        <a href={resolve('/user/[id]', { id: comment.by })}><strong>{comment.by}</strong></a>
      {:else}
        [deleted]
      {/if}
      &nbsp;<time datetime={isoTime(comment.time)}>{timeAgo(comment.time)}</time>
    </div>

    {#if !collapsed}
      {#if comment.text}
        <div class="comment-content">{@html comment.text}</div>
      {/if}
      {#if comment.kids.length}
        <div class="comment-children">
          {#each comment.kids as kid (kid.id)}
            <Self comment={kid} />
          {/each}
        </div>
      {/if}
    {/if}
  </article>
{/if}
