// apps/hackernews-vue/src/components/information.vue
<script setup lang="ts">
  import { formatDistance } from 'date-fns'

  const { story } = defineProps<{ story: StoryData }>()
  const createdTime = story.time && formatDistance(story.time * 1000, new Date(), { addSuffix: true })
</script>

<template>
  <p class="subtitle" v-if="story.type === 'job'">
    {{ createdTime }} | 
  </p>

  <p class="subtitle" v-else-if="story.descendants && story.descendants > 0">
    {{ story.score }} points by
    <!-- <router-link to="`/user/${story.by}`"> -->
      <b>{{ story.by }}</b>
    <!-- </router-link> -->
    {{ createdTime }} | 
    <!-- <router-link to="`/comments/${story.id}`"> -->
      {{ story.descendants }} comments
    <!-- </router-link> -->
  </p>

  <p class="subtitle" v-else>
    {{ story.score }} points by
    <!-- <router-link to="`/user/${story.by}`"> -->
      <b>{{ story.by }}</b>
    <!-- </router-link> -->
    {{ createdTime }} | 
  </p>
</template>

<style scoped>
  .subtitle {
    margin-top: 5px;
    color: var(--gray);
    font-size: 11px;
  }

  .subtitle > a {
    color: var(--gray);
  }

  @media only screen and (max-width: 400px) {
    .subtitle {
      font-size: 11px;
    }
  }
</style>

// apps/hackernews-svelte/src/lib/components/information.svelte
<script lang='ts'>
  import { formatDistance } from 'date-fns'

	export let data: StoryData
	export let showText: boolean = false

  const createdTime = data.time && formatDistance(data.time * 1000, new Date(), { addSuffix: true })
</script>

{#if data.type === 'job'}
  <p class='subtitle'>{createdTime}</p>
{:else if data.descendants && data.descendants > 0}
  <p class='subtitle'>
    {data.score} points by
    <a href={`/user/${data.by}`}><strong>{data.by}</strong></a> |
    <a href={`/comments/${data.id}`}>{data.descendants} comments</a>
  </p>
{:else}
  <p class='subtitle'>
    {data.score} points by <a href={`/user/${data.by}`}><strong>{data.by}</strong></a>
  </p>
{/if}

{#if showText && data.text}
  <div class='text'>{@html data.text}</div>
{/if}

<style>
  .subtitle {
    margin-top: 5px;
    color: var(--gray);
    font-size: 11px;
  }

  .subtitle > a {
    color: var(--gray);
  }

  .text {
    margin-top: 15px;
    margin-left: 6px;
    font-size: 12px;
    color: var(--gray);
  }

  .text p {
    margin: 10px 0;
  }

  .text code, .text pre {
    white-space: pre-wrap;
  }

  @media only screen and (max-width: 400px) {
    .subtitle {
      font-size: 11px;
    }
  }
</style>
