// apps/hackernews-solid/src/components/story-list.tsx
import { firstItemIndex, type StoryData } from '@repo/hn-core'
import { For, Show } from 'solid-js'
import { hidden } from '~/lib/prefs'
import { Story } from './story'

interface Props {
  stories: StoryData[]
  label: string
  page?: number
  hideable?: boolean
}

export function StoryList(props: Props) {
  const visible = () =>
    props.hideable ? props.stories.filter((s) => !hidden.has(s.id)) : props.stories

  return (
    <Show when={visible().length} fallback={<p class="status">Nothing here yet.</p>}>
      <ol class="story-list" aria-label={props.label} start={firstItemIndex(props.page ?? 1)}>
        <For each={visible()}>
          {(story) => (
            <li>
              <Story story={story} hideable={props.hideable} />
            </li>
          )}
        </For>
      </ol>
    </Show>
  )
}

// apps/hackernews-svelte/src/lib/components/story-list.svelte
<script lang="ts">
  import { firstItemIndex, type StoryData } from '@repo/hn-core'
  import { prefs } from '$lib/prefs.svelte'
  import Story from './story.svelte'

  let {
    stories,
    label,
    page = 1,
    hideable = false,
  }: { stories: StoryData[]; label: string; page?: number; hideable?: boolean } = $props()

  const visible = $derived(hideable ? stories.filter((s) => !prefs.hidden.has(s.id)) : stories)
</script>

{#if visible.length}
  <ol class="story-list" aria-label={label} start={firstItemIndex(page)}>
    {#each visible as story (story.id)}
      <li><Story {story} {hideable} /></li>
    {/each}
  </ol>
{:else}
  <p class="status">Nothing here yet.</p>
{/if}
