// apps/hackernews-next/src/components/stories-page.tsx
import { getPage, STORY_TYPE_TITLES, type StoryData, type StoryType } from '@repo/hn-core'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import { loadStories } from '@/lib/data'
import { param } from '@/lib/meta'
import { Loading } from './loading'
import { LoadError } from './load-error'
import { Pager } from './pager'
import { StoryList } from './story-list'

type SearchParams = Promise<Record<string, string | string[] | undefined>>

function title(type: StoryType, page: number) {
  return STORY_TYPE_TITLES[type] + (page > 1 ? ` (page ${page})` : '')
}

export async function storiesMetadata(type: StoryType, searchParams: SearchParams) {
  const page = getPage(param((await searchParams).page))
  return { title: title(type, page) } satisfies Metadata
}

/** A story list page: the shell renders at once and the 30 stories stream in. */
export async function StoriesPage({
  type,
  searchParams,
}: {
  type: StoryType
  searchParams: SearchParams
}) {
  const page = getPage(param((await searchParams).page))
  const { pageCount, stories } = await loadStories(type, page)

  return (
    <>
      <h1 className="visually-hidden">{title(type, page)}</h1>
      <Suspense key={`${type}:${page}`} fallback={<Loading label="Loading stories" lines={12} />}>
        <Stories stories={stories} page={page} pageCount={pageCount} type={type} />
      </Suspense>
    </>
  )
}

async function Stories({
  stories,
  page,
  pageCount,
  type,
}: {
  stories: Promise<StoryData[]>
  page: number
  pageCount: number
  type: StoryType
}) {
  const items = await stories.catch(() => null)
  if (!items) return <LoadError what="stories" />
  return (
    <>
      <StoryList stories={items} label="Stories" page={page} hideable />
      <Pager page={page} pageCount={pageCount} href={(p) => `/${type}?page=${p}`} />
    </>
  )
}

// apps/hackernews-nuxt/app/components/stories-page.vue
<script setup lang="ts">
import { getPage, STORY_TYPE_TITLES, type StoryType } from '@repo/hn-core'

const { type } = defineProps<{ type: StoryType }>()

const route = useRoute()
const page = computed(() => getPage(queryString(route.query.page)))

// Rendered on the server; on client-side navigation the page switches at once and shows a
// skeleton while the stories load.
const { data, status, refresh } = useLazyAsyncData(
  () => `stories:${type}:${page.value}`,
  () => loadStories(type, page.value),
)

const title = computed(
  () => STORY_TYPE_TITLES[type] + (page.value > 1 ? ` (page ${page.value})` : ''),
)
useHead({ title })
</script>

<template>
  <h1 class="visually-hidden">{{ title }}</h1>

  <LoadError v-if="status === 'error'" what="stories" @retry="refresh()" />
  <template v-else-if="data && status === 'success'">
    <StoryList :stories="data.stories" label="Stories" :page="page" hideable />
    <Pager :page="page" :page-count="data.pageCount" :href="(p) => `/${type}?page=${p}`" />
  </template>
  <Loading v-else label="Loading stories" :lines="12" />
</template>
