// apps/hackernews-svelte/src/lib/components/story-list.svelte
<script lang="ts">
  import { firstItemIndex, type StoryData } from '@repo/hn-core'
  import { prefs } from '$lib/prefs.svelte'
  import Story from './story.svelte'

  let {
    stories,
    label,
    page = 1,
    hideable = false,
  }: { stories: StoryData[]; label: string; page?: number; hideable?: boolean } = $props()

  const visible = $derived(hideable ? stories.filter((s) => !prefs.hidden.has(s.id)) : stories)
</script>

{#if visible.length}
  <ol class="story-list" aria-label={label} start={firstItemIndex(page)}>
    {#each visible as story (story.id)}
      <li><Story {story} {hideable} /></li>
    {/each}
  </ol>
{:else}
  <p class="status">Nothing here yet.</p>
{/if}

// apps/hackernews-nuxt/app/components/story-list.vue
<script setup lang="ts">
import { firstItemIndex, type StoryData } from '@repo/hn-core'

const {
  stories,
  label,
  page = 1,
  hideable = false,
} = defineProps<{ stories: StoryData[]; label: string; page?: number; hideable?: boolean }>()

const prefs = usePrefs()
const visible = computed(() =>
  hideable ? stories.filter((s) => !prefs.hidden.has(s.id)) : stories,
)
</script>

<template>
  <ol v-if="visible.length" class="story-list" :aria-label="label" :start="firstItemIndex(page)">
    <li v-for="story in visible" :key="story.id">
      <StoryItem :story="story" :hideable="hideable" />
    </li>
  </ol>
  <p v-else class="status">Nothing here yet.</p>
</template>
