// apps/hackernews-qwik/src/components/user-comment.tsx
import { component$ } from '@builder.io/qwik'
import { Link } from '@builder.io/qwik-city'
import type { UserComment as UserCommentData } from '@repo/hn-core'
import { RelTime } from './rel-time'

export const UserComment = component$<{ comment: UserCommentData }>(({ comment }) => (
  <article class="comment">
    <div class="comment-header">
      <Link href={`/user/${comment.by}`} prefetch={false}>
        <strong>{comment.by}</strong>
      </Link>
      &nbsp;
      <RelTime unix={comment.time} />
      {comment.storyId > 0 && (
        <>
          &nbsp;on&nbsp;
          <Link href={`/comments/${comment.storyId}`} prefetch={false}>
            {comment.storyTitle}
          </Link>
        </>
      )}
    </div>
    <div class="comment-content" dangerouslySetInnerHTML={comment.text} />
  </article>
))

// apps/hackernews-solid/src/components/user-comment.tsx
import type { UserComment as UserCommentData } from '@repo/hn-core'
import { Show } from 'solid-js'
import { RelTime } from './rel-time'

export function UserComment(props: { comment: UserCommentData }) {
  return (
    <article class="comment">
      <div class="comment-header">
        <a href={`/user/${props.comment.by}`}>
          <strong>{props.comment.by}</strong>
        </a>
        &nbsp;
        <RelTime unix={props.comment.time} />
        <Show when={props.comment.storyId}>
          &nbsp;on&nbsp;
          <a href={`/comments/${props.comment.storyId}`}>{props.comment.storyTitle}</a>
        </Show>
      </div>
      <div class="comment-content" innerHTML={props.comment.text} />
    </article>
  )
}
