// apps/hackernews-qwik/src/routes/user/[id]/index.tsx
import { component$ } from '@builder.io/qwik'
import { routeLoader$, type DocumentHead } from '@builder.io/qwik-city'
import { formatJoinDate } from '@repo/hn-core'
import { NotFound } from '~/components/not-found'
import { Submissions } from '~/components/submissions'
import { loadUser } from '~/lib/data'

export const useUser = routeLoader$(async ({ params, status }) => {
  const data = await loadUser(params.id)
  if (!data) status(404)
  return data
})

export default component$(() => {
  const data = useUser().value
  if (!data) return <NotFound />
  const { user, stories } = data

  return (
    <>
      <h1 class="visually-hidden">Profile: {user.id}</h1>

      <dl class="user-grid">
        <dt>User:</dt>
        <dd>{user.id}</dd>
        <dt>Karma:</dt>
        <dd>{user.karma}</dd>
        <dt>Created:</dt>
        <dd>{formatJoinDate(user.created)}</dd>
        {user.about && (
          <>
            <dt>About:</dt>
            <dd class="about" dangerouslySetInnerHTML={user.about} />
          </>
        )}
      </dl>

      <Submissions key={user.id} user={user.id} firstStories={stories} />
    </>
  )
})

export const head: DocumentHead = ({ resolveValue }) => {
  const data = resolveValue(useUser)
  return { title: data ? `Profile: ${data.user.id}` : 'Not found' }
}

// apps/hackernews-next/src/app/user/[id]/page.tsx
import { formatJoinDate } from '@repo/hn-core'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { Submissions } from '@/components/submissions'
import { loadUser } from '@/lib/data'

export async function generateMetadata({ params }: PageProps<'/user/[id]'>): Promise<Metadata> {
  const data = await loadUser((await params).id)
  return data ? { title: `Profile: ${data.user.id}` } : { title: 'Not found' }
}

export default async function UserPage({ params }: PageProps<'/user/[id]'>) {
  const data = await loadUser((await params).id)
  if (!data) notFound()
  const { user, stories } = data

  return (
    <>
      <h1 className="visually-hidden">Profile: {user.id}</h1>

      <dl className="user-grid">
        <dt>User:</dt>
        <dd>{user.id}</dd>
        <dt>Karma:</dt>
        <dd>{user.karma}</dd>
        <dt>Created:</dt>
        <dd>{formatJoinDate(user.created)}</dd>
        {user.about && (
          <>
            <dt>About:</dt>
            <dd className="about" dangerouslySetInnerHTML={{ __html: user.about }} />
          </>
        )}
      </dl>

      <Submissions key={user.id} user={user.id} firstStories={stories} />
    </>
  )
}
