// apps/hackernews-svelte/src/routes/user/[id]/+page.svelte
<script lang="ts">
  import { formatJoinDate } from '@repo/hn-core'
  import Submissions from '$lib/components/submissions.svelte'
  import { pageTitle } from '$lib/meta'
  import type { PageProps } from './$types'

  let { data }: PageProps = $props()
</script>

<svelte:head>
  <title>{pageTitle(`Profile: ${data.user.id}`)}</title>
</svelte:head>

<h1 class="visually-hidden">Profile: {data.user.id}</h1>

<dl class="user-grid">
  <dt>User:</dt>
  <dd>{data.user.id}</dd>
  <dt>Karma:</dt>
  <dd>{data.user.karma}</dd>
  <dt>Created:</dt>
  <dd>{formatJoinDate(data.user.created)}</dd>
  {#if data.user.about}
    <dt>About:</dt>
    <dd class="about">{@html data.user.about}</dd>
  {/if}
</dl>

{#key data.user.id}
  <Submissions user={data.user.id} firstStories={data.stories} />
{/key}

// apps/hackernews-next/src/app/user/[id]/page.tsx
import { formatJoinDate } from '@repo/hn-core'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { Submissions } from '@/components/submissions'
import { loadUser } from '@/lib/data'

export async function generateMetadata({ params }: PageProps<'/user/[id]'>): Promise<Metadata> {
  const data = await loadUser((await params).id)
  return data ? { title: `Profile: ${data.user.id}` } : {}
}

export default async function UserPage({ params }: PageProps<'/user/[id]'>) {
  const data = await loadUser((await params).id)
  if (!data) notFound()
  const { user, stories } = data

  return (
    <>
      <h1 className="visually-hidden">Profile: {user.id}</h1>

      <dl className="user-grid">
        <dt>User:</dt>
        <dd>{user.id}</dd>
        <dt>Karma:</dt>
        <dd>{user.karma}</dd>
        <dt>Created:</dt>
        <dd>{formatJoinDate(user.created)}</dd>
        {user.about && (
          <>
            <dt>About:</dt>
            <dd className="about" dangerouslySetInnerHTML={{ __html: user.about }} />
          </>
        )}
      </dl>

      <Submissions key={user.id} user={user.id} firstStories={stories} />
    </>
  )
}
