// apps/hackernews-svelte/src/routes/comments/[id]/+page.svelte
<script lang="ts">
  import { isoTime, timeAgo } from '@repo/hn-core'
  import { resolve } from '$app/paths'
  import Comment from '$lib/components/comment.svelte'
  import LoadError from '$lib/components/load-error.svelte'
  import Loading from '$lib/components/loading.svelte'
  import Story from '$lib/components/story.svelte'
  import { pageTitle } from '$lib/meta'
  import type { PageProps } from './$types'

  let { data }: PageProps = $props()

  const item = $derived(data.item)
  const title = $derived(item.type === 'comment' ? `Comment by ${item.by}` : item.title)
</script>

<svelte:head>
  <title>{pageTitle(title)}</title>
</svelte:head>

{#if item.type === 'comment'}
  <article class="comment">
    <h1 class="comment-header">
      <a href={resolve('/user/[id]', { id: item.by })}>{item.by}</a>
      &nbsp;<time datetime={isoTime(item.time)}>{timeAgo(item.time)}</time>
      &nbsp;|&nbsp;<a href={resolve('/comments/[id]', { id: String(item.parent) })}>parent</a>
    </h1>
    <div class="comment-content">{@html item.text}</div>
  </article>
{:else}
  <Story story={item} heading="h1" showText />
{/if}

<section class="comment-list" aria-label="Comments">
  {#await data.thread}
    <Loading label="Loading comments" />
  {:then comments}
    {#each comments as comment (comment.id)}
      <Comment {comment} />
    {:else}
      <p class="status">No comments yet.</p>
    {/each}
  {:catch}
    <LoadError what="comments" />
  {/await}
</section>

// apps/hackernews-next/src/app/comments/[id]/page.tsx
import type { ThreadComment } from '@repo/hn-core'
import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Suspense } from 'react'
import { Comment } from '@/components/comment'
import { LoadError } from '@/components/load-error'
import { Loading } from '@/components/loading'
import { Story } from '@/components/story'
import { Time } from '@/components/time'
import { loadItem, loadThread } from '@/lib/data'

export async function generateMetadata({ params }: PageProps<'/comments/[id]'>): Promise<Metadata> {
  const item = await loadItem((await params).id)
  if (!item) return {}
  return { title: item.type === 'comment' ? `Comment by ${item.by}` : item.title }
}

export default async function CommentsPage({ params }: PageProps<'/comments/[id]'>) {
  const { id } = await params
  const item = await loadItem(id)
  if (!item) notFound()

  return (
    <>
      {item.type === 'comment' ? (
        <article className="comment">
          <h1 className="comment-header">
            <Link href={`/user/${item.by}`}>{item.by}</Link>
            &nbsp;
            <Time unix={item.time} />
            &nbsp;|&nbsp;<Link href={`/comments/${item.parent}`}>parent</Link>
          </h1>
          <div className="comment-content" dangerouslySetInnerHTML={{ __html: item.text }} />
        </article>
      ) : (
        <Story story={item} heading="h1" showText />
      )}

      <section className="comment-list" aria-label="Comments">
        <Suspense fallback={<Loading label="Loading comments" />}>
          <Thread thread={loadThread(id)} />
        </Suspense>
      </section>
    </>
  )
}

async function Thread({ thread }: { thread: Promise<ThreadComment[]> }) {
  const comments = await thread.catch(() => null)
  if (!comments) return <LoadError what="comments" />
  if (!comments.length) return <p className="status">No comments yet.</p>
  return comments.map((comment) => <Comment key={comment.id} comment={comment} />)
}
