// apps/hackernews-qwik/src/routes/layout.tsx
import { component$, Slot, useContextProvider, useStore, useVisibleTask$ } from '@builder.io/qwik'
import { routeLoader$ } from '@builder.io/qwik-city'
import { parseTheme, THEME_COOKIE } from '@repo/hn-core'
import { Header } from '~/components/header'
import { loadPrefs, PrefsContext, type Prefs } from '~/lib/prefs'

export const useSavedTheme = routeLoader$(({ cookie }) =>
  parseTheme(cookie.get(THEME_COOKIE)?.value),
)

export default component$(() => {
  const savedTheme = useSavedTheme()
  const prefs = useStore<Prefs>({ hidden: [], read: [] })
  useContextProvider(PrefsContext, prefs)

  // localStorage only exists in the browser.
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(() => loadPrefs(prefs))

  return (
    <div class="app">
      <Header savedTheme={savedTheme.value} />
      <main class="main">
        <Slot />
      </main>
      <footer class="footer">
        ©{new Date().getFullYear()} Karsanda ·{' '}
        <a href="https://github.com/karsanda/monorepo/tree/main/apps/hackernews-qwik">Source</a>
      </footer>
    </div>
  )
})

// apps/hackernews-next/src/app/layout.tsx
import { parseTheme, THEME_COOKIE } from '@repo/hn-core'
import type { Metadata, Viewport } from 'next'
import { cookies } from 'next/headers'
import type { ReactNode } from 'react'
import { Header } from '@/components/header'
import { SwRegister } from '@/components/sw-register'
import { APP_NAME } from '@/lib/meta'
import './globals.css'

export const metadata: Metadata = {
  title: { template: `%s | ${APP_NAME}`, default: APP_NAME },
  description: 'Hacker News reader built with Next.js',
  icons: { icon: '/favicon.svg', apple: '/apple-touch-icon.png' },
}

export const viewport: Viewport = { themeColor: '#0070f3' }

export default async function RootLayout({ children }: { children: ReactNode }) {
  // Rendering the saved theme on the server means dark mode doesn't flash on load.
  const theme = parseTheme((await cookies()).get(THEME_COOKIE)?.value)

  return (
    <html lang="en" data-theme={theme}>
      <body>
        <div className="app">
          <Header savedTheme={theme} />
          <main className="main">{children}</main>
          <footer className="footer">
            ©{new Date().getFullYear()} Karsanda ·{' '}
            <a href="https://github.com/karsanda/monorepo/tree/main/apps/hackernews-next">Source</a>
          </footer>
        </div>
        <SwRegister />
      </body>
    </html>
  )
}
