// apps/hackernews-qwik/src/components/stories-page.tsx
import { component$ } from '@builder.io/qwik'
import type { RequestEventLoader } from '@builder.io/qwik-city'
import {
  getPage,
  isStoryType,
  STORY_TYPE_TITLES,
  type StoryData,
  type StoryType,
} from '@repo/hn-core'
import { loadStories } from '~/lib/data'
import { LoadError } from './load-error'
import { NotFound } from './not-found'
import { Pager } from './pager'
import { StoryList } from './story-list'

export type StoriesData =
  | null
  | { type: StoryType; page: number; failed: true }
  | { type: StoryType; page: number; failed: false; pageCount: number; stories: StoryData[] }

/** Loads a story list page for a route loader; `null` (with a 404) for unknown types. */
export async function storiesLoader(type: string, { url, status }: RequestEventLoader) {
  if (!isStoryType(type)) {
    status(404)
    return null
  }
  const page = getPage(url.searchParams.get('page'))
  try {
    return { type, page, failed: false as const, ...(await loadStories(type, page)) }
  } catch {
    status(502)
    return { type, page, failed: true as const }
  }
}

export const storiesTitle = (data: StoriesData) =>
  data ? STORY_TYPE_TITLES[data.type] + (data.page > 1 ? ` (page ${data.page})` : '') : 'Not found'

export const StoriesPage = component$<{ data: StoriesData }>(({ data }) => {
  if (!data) return <NotFound />
  return (
    <>
      <h1 class="visually-hidden">{storiesTitle(data)}</h1>
      {data.failed ? (
        <LoadError what="stories" />
      ) : (
        <>
          <StoryList stories={data.stories} label="Stories" page={data.page} hideable />
          <Pager page={data.page} pageCount={data.pageCount} prefix={`/${data.type}?page=`} />
        </>
      )}
    </>
  )
})

// apps/hackernews-next/src/components/stories-page.tsx
import { getPage, STORY_TYPE_TITLES, type StoryData, type StoryType } from '@repo/hn-core'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import { loadStories } from '@/lib/data'
import { param } from '@/lib/meta'
import { Loading } from './loading'
import { LoadError } from './load-error'
import { Pager } from './pager'
import { StoryList } from './story-list'

type SearchParams = Promise<Record<string, string | string[] | undefined>>

function title(type: StoryType, page: number) {
  return STORY_TYPE_TITLES[type] + (page > 1 ? ` (page ${page})` : '')
}

export async function storiesMetadata(type: StoryType, searchParams: SearchParams) {
  const page = getPage(param((await searchParams).page))
  return { title: title(type, page) } satisfies Metadata
}

/** A story list page: the shell renders at once and the 30 stories stream in. */
export async function StoriesPage({
  type,
  searchParams,
}: {
  type: StoryType
  searchParams: SearchParams
}) {
  const page = getPage(param((await searchParams).page))
  const { pageCount, stories } = await loadStories(type, page)

  return (
    <>
      <h1 className="visually-hidden">{title(type, page)}</h1>
      <Suspense key={`${type}:${page}`} fallback={<Loading label="Loading stories" lines={12} />}>
        <Stories stories={stories} page={page} pageCount={pageCount} type={type} />
      </Suspense>
    </>
  )
}

async function Stories({
  stories,
  page,
  pageCount,
  type,
}: {
  stories: Promise<StoryData[]>
  page: number
  pageCount: number
  type: StoryType
}) {
  const items = await stories.catch(() => null)
  if (!items) return <LoadError what="stories" />
  return (
    <>
      <StoryList stories={items} label="Stories" page={page} hideable />
      <Pager page={page} pageCount={pageCount} href={(p) => `/${type}?page=${p}`} />
    </>
  )
}
